name: Release ARM
on:
  push:
    tags:
      - v*
      - pre-rel-*

jobs:
  create-release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/github-script@v3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let tag = context.payload.ref.replace(/.*\//, '');
            let buildNo = context.runNumber;
            let versionName = tag.replace(/^pre-rel-/,'');
            try {
              let release =  await github.request("GET /repos/:owner/:repo/releases/tags/:tag", {
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag
              });
            }
            catch(e) {
              let body = ["TODO"].join("\n");

              let release =  await github.request("POST /repos/:owner/:repo/releases", {
                owner: context.repo.owner,
                repo: context.repo.repo,
                data: {
                  tag_name: tag,
                  prerelease: true,
                  body: body,
                  name: `${versionName} #${buildNo}`
                }
              });
              console.log(release.data.upload_url);
            }

  build:
    name: Build Release
    needs:
      - create-release
    runs-on: ubuntu-latest
    env:
      OPENSSL_STATIC: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          lfs: true

      - name: Get upload url
        id: release_upload_url
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
              let tag = context.payload.ref.replace(/.*\//, '');
              let release =  await github.request("GET /repos/:owner/:repo/releases/tags/:tag", {
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag
              });
              console.log(release.data.upload_url);
              return release.data.upload_url

      - name: Install last stable Rust cross compiler
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true

      - name: Build proxy
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: -p ya-http-proxy --bin ya-http-proxy --features bin --release --target aarch64-unknown-linux-musl

      - name: Build runtime
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-musl

      - name: Pack
        id: pack
        shell: bash
        env:
          GITHUB_REF: ${{ github.ref }}
          OS_NAME: linux
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          TARGET_DIR=releases/ya-runtime-http-auth-linux-${TAG_NAME}

          ls -la target
          mkdir -p "$TARGET_DIR/ya-runtime-http-auth"
          #strip "target/aarch64-unknown-linux-musl/release/ya-runtime-http-auth"
          #strip "target/aarch64-unknown-linux-musl/release/ya-http-proxy"

          set -x
          cp target/aarch64-unknown-linux-musl/release/ya-runtime-http-auth "$TARGET_DIR/ya-runtime-http-auth/"
          cp target/aarch64-unknown-linux-musl/release/ya-http-proxy "$TARGET_DIR/ya-runtime-http-auth/"
          cp conf/ya-runtime-http-auth.json "$TARGET_DIR/"
          (cd releases && tar czvf "ya-runtime-http-auth-${OS_NAME}-${TAG_NAME}.tar.gz" "ya-runtime-http-auth-${OS_NAME}-${TAG_NAME}")

          echo "::set-output name=artifact::ya-runtime-http-auth-${OS_NAME}-${TAG_NAME}.tar.gz"
          echo "::set-output name=media::application/tar+gzip"

      - name: Upload
        run: echo todo upload ${{ steps.pack.outputs.artifact }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_upload_url.outputs.result }}
          asset_path: ./releases/${{ steps.pack.outputs.artifact }}
          asset_name: ${{ steps.pack.outputs.artifact }}
          asset_content_type: ${{ steps.pack.outputs.media }}
 
